### ISSUE TITLE
Warnings in cache.php

### ISSUE THREAD

**Issue by dlugosch** [ccl/dokuwiki-plugin-datatemplate#1]
Hi! On my installation the plugin shows several warnings on any page using datatemplatelist.

The warnigs (each showing several times) are:

Warning: array_flip() [function.array-flip]: Can only flip STRING and INTEGER values! in C:\Program Files\EasyPHP-5.3.5.0\www\lib\plugins\datatemplate\syntax\inc\cache.php on line 90

and:

Warning: array_diff_key() [function.array-diff-key]: Argument #2 is not an array in C:\Program Files\EasyPHP-5.3.5.0\www\lib\plugins\datatemplate\syntax\inc\cache.php on line 105

The wiki source used for displaying is:

---- datatemplatelist ----
template: teamtemplatelist
cols    : titleprefix, firstname, lastname, titlesuffix, room, phone, mobile, email_mail, type, active, imgname, fachgebiet
sort    : lastname
filter  : %pageid%~dat:team:*
and     : type=secretary
## and     : active=yes

The wiki source for storing the data is:

---- datatemplateentry ----
template   : teamtemplate #Diese Zeile bitte nicht veraendern
titleprefix : Dipl.-Inf.
firstname  : Carsten
lastname   : Dlugosch
titlesuffix :  ##Titel nachgestellt (optional)##
type       : scientific #es gibt folgende Typen: "management" "secretary" "scientific" "guest" "administrative" "technical"
fachgebiet : lfe
active     : yes #yes=aktueller MA, no=ehemaliger MA
room       : MW 0335
phone      : +49 89 289 15019
mobile     : ##Mobiltelefon (optional)##
email_mail : dlugosch@lfe.mw.tum.de
## imgname    : Carsten-Dlugosch.jpg

Further informations:
In the first warning the array_flip function seems to be called using an array as argument:
e.g. array_flip ( array (0 => array (0 => ' dat:team:andreas-haslbeck'), 1 => array (0 => ' dat:team:carsten-dlugosch'), 2 => array (0 => ' dat:team:florian-engstler')) )

In the second warning the array_diff_key is called with invalid secon argument
array_diff_key ( array (), NULL )

Greetings
Carsten

**Comment by ccl** [comment]
Hello Carsten,

thanks for pointing this out! I had noticed recently that pages were not removed from the cache properly where needed, and this issue was actually at the heart of it.

I released a new version in the "master" branch, where this issue has been addressed. You can use the Dokuwiki Plugin Manager to update to this version. Please tell me if it solves your problem, and if new problems have been introduced.

Best,
Christoph
