### ISSUE TITLE
use 'cols' in stead of 'headers'

### ISSUE THREAD

**Issue by Klap-in** [ccl/dokuwiki-plugin-datatemplate#11]
The code uses $data['headers']. This list contains headers for the datatable, which has translated string for the some column names.
https://github.com/ccl/dokuwiki-plugin-datatemplate/blob/master/syntax/list.php#L197

I like to change the behaviour by using cols instead of headers. This means that the current placeholder syntax will break. What's your opinion on this?

When you agree, i will submit a PR with these changes.

Some debug info:

Column definition:

```
cols    : %title%, %lastmod%, imgname, phone, email_mail
```

Some sample data for $data['headers'], with language depend titles:

```
with English titles:
Array(
    [0] => Page
    [1] => Last Modified
    [2] => imgname
    [3] => phone
    [4] => email
    [5] => %pageid%
)
with Dutch titles:
Array(
    [0] => Pagina
    [1] => Laatst Gewijzigd
    [2] => imgname
    [3] => phone
    [4] => email
    [5] => %pageid%
)
```

Some sample data for $clist = array_keys($data['cols']):

```
Array(
    [0] => %title%
    [1] => %lastmod%
    [2] => imgname
    [3] => phone
    [4] => email
    [5] => %pageid%
)
```

**Comment by ccl** [comment]
First of all, I'd like to thank you for your work on this plugin. Your patch to make it work with sqlite3 was highly appreciated, and so are your contributions to the plugin's Dokuwiki page!

I did not notice that the headers are language dependent, and I completely agree, that using the 'cols' attribute for the placeholders is much more natural. This alone is reason enough to implement the changes that you propose.

It is unfortunate that this will require changes to templates that use certain fields. But I assume that many users, who really wanted to use e.g. %lastmod% in their template, did not figure out that the proper placeholder is @@Last Modified@@, and used some kind of work around instead. With your change, at future users will have less trouble, and if current users are properly informed, they should quickly be able to change their templates.

Ideally, one could provide some kind of migration script, which automatically scans for deprecated placeholders...
