### ISSUE TITLE
2-column tables malformed when fields are empty

### ISSUE THREAD

**Issue by bitinerant** [ccl/dokuwiki-plugin-datatemplate#2]
Something about datatemplate placeholders messes up DokuWiki tables when the data field is empty.

My data entry page contains something like this:

<pre>
---- datatemplateentry ----
template          : template
fullname          : Smith, Jack
email1_mail       : jsmith@gmail.com
email1note        : personal
email2_mail       : secondemail@mail.com
email2note        : alternate personal
email3_mail       : thirdemail@yahoomail.com
email3note        : work email
email4_mail       : 
email4note        : 
----
</pre>

and my [[template]] contains:

<pre>
^Email           ^                ^
|  @@email1note@@|**@@email1@@**  |
|  @@email2note@@|**@@email2@@**  |
|  @@email3note@@|**@@email3@@**  |
|  @@email4note@@|**@@email4@@**  |
</pre>

There are two problems with the way the table is displayed.  First, the fourth row is very short, which can be fixed by using a non-breaking space somewhere on it (e.g. U+2007).  However, the second problem is that the outer box is not drawn on the right or bottom of the last cell.  Is this fixable, or perhaps there is a better way to do what I'm trying to do?

Note that a one-column table for this works fine:

<pre>
^Email           ^
|**@@email1@@**  |
|**@@email2@@**  |
|**@@email3@@**  |
|**@@email4@@**  |
</pre>

**Comment by ccl** [comment]
This was due to a too greedy regular expression when removing unused placeholders. Fixed in upcoming release.
