### ISSUE TITLE
datatemplate plugin incompatible with data plugin 2016-03-11

### ISSUE THREAD

**Issue by tmo26** [ccl/dokuwiki-plugin-datatemplate#21]
Release 2015-08-10a "Detritus"
data plugin Installed version: 2016-01-24

datatemplate plugin:
Installed version:    2011-08-27 <- wrong due to #19 
Your last update:    Wed, 03 Feb 2016 23:46:58 +0100
Available version:    2014-01-12 <- installed

When installing data plugin version 2016-03-11, the wiki stops working and shows only blank white pages, which makes it completely unusable.

Solution: Disable datatemplate plugin.

The reason for the datatemplate breaking the wiki: see https://github.com/splitbrain/dokuwiki-plugin-data/issues/191

> The only change made between the releases is the renaming of a constructor. That should be unproblematic _unless something calls that constructor directly by it's name instead of just calling new on the class name_. I don't see something like this in the data plugin itself, so it could only happen when a different plugin makes use of the data plugin.

Could you please fix this error by adapting the datatemplate plugin to the changes made to the data plugin in version 2016-03-11?

**Comment by butch2k** [comment]
Edit syntax/list.php 
replace parent::syntax_plugin_data_table();
by parent::__construct();

**Comment by tmo26** [comment]
Confirmed working!
Please include this change in the official distribution of the plugin on https://www.dokuwiki.org/plugin:datatemplate
