### ISSUE TITLE
Exdessive datatemplateentry added to %class%

### ISSUE THREAD

**Issue by Vovanium** [ccl/dokuwiki-plugin-datatemplate#3]
When write enty like

```
---- datatemplateentry sample ----
----
```

%class% field expected to be "sample" but appears as "datatemplateentry sample" and thus messes up filtering using class.

Code @ line #30 fixes this:

```
        // strip datatemplateentry to get right classes
        $match = preg_replace('/datatemplateentry/', '', $match, 1);
```

To get datatemplate class rendered change line #86 to

```
        $R->doc .= '<div class="datatemplateentry ' . $data['classes'] . '">';
```

**Comment by ccl** [comment]
You are absolutely right! Thank you for pointing this out and providing a solution. Fixed in upcoming release.

And I am sorry for being so slow. Unfortunately I only rarely find time to look into problems that do not directly concern me.
