### ISSUE TITLE
Title processing require improvement

### ISSUE THREAD

**Issue by Vovanium** [ccl/dokuwiki-plugin-datatemplate#4]
When there's a title inside a template then title in the data plugin and dokuwiki's own index gets desynchronized.
Dokuwiki index ignore title inside a template but datatemplateentry override any title from outside by the title inside template.

Say the template is

```
====== A ======
```

And the file is

```
====== B ======
---- datatemplateentry ----
template: template
----
```

then title in database will be "A", but in the wiki index (in page list for example) it will be "B".

**Comment by Vovanium** [comment]
First fast and dirty hack is to add following code to _saveData(...) method:

```
        if($title) {
            parent::_saveData($data, $id, $title);
            return;
        }
```

This checks if a title is already set outside the template (template then may have section headers which will not be exposed as page title).

**Comment by ccl** [comment]
Should be fixed in current release.
